

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./react_redux
    container_name: frontend_container
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
